#!/bin/sh
# regenerate(): the pinned certificate must reach client.toml.
#
# WHY. regenerate writes the pinned certificate to endpoint.pem (PEM is
# multi-line and never a record value) and hands it to gen-config. The
# second argument of gen-config is a FILE PATH to read the PEM from; passing
# the certificate content instead silently dropped the pin — client.toml
# ended up with `certificate = ""` and the client fell back to the system
# trust store. This test pins the calling convention: gen-config receives
# the pem path, and only the records path when nothing is pinned.
#
# The real regenerate is used (test_init_reload.sh stubs it because that
# test watches the apply flow, not the generation), with the tools it calls
# replaced by logging stubs — the same arrangement the reload test uses.
. "$(dirname "$0")/lib.sh"

INIT="packages/luci-app-trusttunnel/root/etc/init.d/trusttunnel"

sandbox="$TT_TEST_TMP/sandbox"
bin="$sandbox/bin"
mkdir -p "$bin" "$sandbox/lib" "$sandbox/out"

TT_CALLS="$sandbox/calls"
TT_NEXT="$sandbox/next.tsv"
TT_CERT_UCI="$sandbox/cert_uci"
export TT_CALLS TT_NEXT TT_CERT_UCI

# The certificate lookup goes through uci; its answer comes from a file so a
# multi-line PEM survives the stub boundary.
cat > "$bin/uci" <<'EOF'
#!/bin/sh
case "$*" in
	"-q get trusttunnel.endpoint.certificate")
		cat "$TT_CERT_UCI" 2>/dev/null
		;;
esac
exit 0
EOF

cat > "$sandbox/lib/uci-export" <<'EOF'
#!/bin/sh
[ "${UCI_EXPORT_RC:-0}" = "0" ] || exit "$UCI_EXPORT_RC"
cat "$TT_NEXT"
EOF

# gen-config records its arguments (count and text) and emits a marker that
# lands in client.toml, so the test can see exactly what it was called with.
cat > "$sandbox/lib/gen-config" <<'EOF'
#!/bin/sh
echo "gen-config $#: $*" >> "$TT_CALLS"
[ "${GEN_RC:-0}" = "0" ] || exit 1
printf 'generated by %s\n' "$*"
exit 0
EOF

chmod +x "$bin/uci" "$sandbox/lib/uci-export" "$sandbox/lib/gen-config"
PATH="$bin:$PATH"
export PATH

# shellcheck disable=SC1090
. "$INIT"

# The paths are computed at the top level of the init script relative to /var,
# so all three are overridden here, exactly as test_init_reload.sh does.
OUTDIR="$sandbox/out"
RECORDS="$OUTDIR/settings.tsv"
LIBDIR="$sandbox/lib"

cat > "$TT_NEXT" <<'EOF'
main.enabled	1
endpoint.hostname	tt.test
endpoint.address	44.55.66.20:8443
endpoint.username	router
endpoint.password	test-pass
EOF

PEM="$OUTDIR/endpoint.pem"
TOML="$OUTDIR/client.toml"

calls() { tr '\n' ' ' < "$TT_CALLS" | sed 's/ $//'; }

setup() {
	: > "$TT_CALLS"
	unset GEN_RC UCI_EXPORT_RC
	export GEN_RC UCI_EXPORT_RC
}

# --- Pinned certificate ------------------------------------------------------

# The whole point: with a pin set, gen-config must receive the pem file path
# as its second argument — not the certificate text.
setup
printf -- '-----BEGIN CERTIFICATE-----\ndummy\n-----END CERTIFICATE-----\n' > "$TT_CERT_UCI"
regenerate
assert_eq "0" "$?" "regenerate succeeds with a pinned certificate"
assert_eq "$(cat "$PEM")" "$(cat "$TT_CERT_UCI")" \
	"the pinned certificate is written verbatim to endpoint.pem"
assert_eq "-rw-------" "$(ls -l "$PEM" | awk '{print $1}')" \
	"endpoint.pem is mode 600"
assert_contains "$(calls)" "gen-config 2: $RECORDS $PEM" \
	"gen-config receives the pem FILE PATH, not the content"
assert_contains "$(cat "$TOML")" "generated by $RECORDS $PEM" \
	"the client.toml generation runs against records and the pem file"
assert_eq "-rw-------" "$(ls -l "$TOML" | awk '{print $1}')" \
	"client.toml is mode 600"
assert_eq "$(cat "$RECORDS")" "$(cat "$TT_NEXT")" \
	"the records file carries the exported state"

# --- No certificate -----------------------------------------------------------

setup
: > "$TT_CERT_UCI"
regenerate
assert_eq "0" "$?" "regenerate succeeds without a certificate"
assert_exit 1 "no endpoint.pem is written without a pin" test -e "$PEM"
assert_contains "$(calls)" "gen-config 1: $RECORDS" \
	"without a pin gen-config receives only the records path"
assert_contains "$(cat "$TOML")" "generated by $RECORDS" \
	"the client.toml generation runs without a pem argument"

# --- Clearing an existing pin --------------------------------------------------

# A reinstall without the pin must not leave the stale pem behind: the client
# would keep trusting a certificate that is no longer configured.
setup
printf -- '-----BEGIN CERTIFICATE-----\nold\n-----END CERTIFICATE-----\n' > "$TT_CERT_UCI"
regenerate
: > "$TT_CERT_UCI"
regenerate
assert_exit 1 "clearing the pin removes endpoint.pem" test -e "$PEM"
assert_eq "gen-config 1: $RECORDS" "$(tail -1 "$TT_CALLS")" \
	"the regenerated config carries no pin"

# --- Failure paths -------------------------------------------------------------

# A uci-export failure must fail the regeneration and must not leave a
# half-written records file behind — it carries the password.
setup
UCI_EXPORT_RC=1
regenerate
assert_eq "1" "$?" "a uci-export failure fails regenerate"
assert_exit 1 "no half-written records file is left behind" \
	test -e "$OUTDIR/settings.tsv.new"

# A gen-config failure must fail the regeneration; the redirect has already
# created client.toml by then, so the file must at least carry no config.
setup
GEN_RC=1
regenerate
assert_eq "1" "$?" "a gen-config failure fails regenerate"
assert_eq "" "$(cat "$TOML")" "a failed generation leaves no client config behind"

tt_test_summary
