#!/bin/sh
# client.toml generator, pinned from the gen-config contract.
#
# gen-config reads the records TSV (sourced records.sh accessors) and an
# optional PEM file, and prints the client.toml consumed by the client
# binary. The key set, values, order and formatting are a hard contract:
# fixed fields stay fixed, scalar strings are TOML-escaped (backslash
# first, then double quote), booleans render lowercase, lists are joined
# with ", " inside square brackets, and the profile mode matrix drives
# vpn_mode/exclusions with the legacy direct list as the fallback.
. "$(dirname "$0")/lib.sh"

GEN=packages/luci-app-trusttunnel/root/usr/libexec/trusttunnel/gen-config

# count_occ <needle> <text> — prints how many times the needle appears.
count_occ() {
    _needle=$1
    _text=$2
    _n=0
    while :; do
        case $_text in
            *"$_needle"*)
                _n=$((_n + 1))
                _text=${_text#*"$_needle"}
                ;;
            *) break ;;
        esac
    done
    printf '%s\n' "$_n"
}

# --- minimal fixture (no profile assigned) --------------------------------------

minimal_out=$(sh "$GEN" tests/fixtures/records/minimal.tsv)

assert_contains "$minimal_out" \
    "# Generated by luci-app-trusttunnel. Do not edit: changes are overwritten." \
    "the output opens with the do-not-edit header"
assert_contains "$minimal_out" 'loglevel = "info"' "loglevel falls back to info"
assert_contains "$minimal_out" 'vpn_mode = "general"' "no profile assigned means general mode"
assert_contains "$minimal_out" "killswitch_enabled = false" "the killswitch is fixed off"
assert_contains "$minimal_out" "post_quantum_group_enabled = true" "post quantum defaults to true"
assert_contains "$minimal_out" "exclusions_tcp_early_ack_enabled = true" "tcp early ack is fixed on"
assert_contains "$minimal_out" "exclusions_preresolve_enabled = true" "preresolve is fixed on"
assert_contains "$minimal_out" "exclusions = []" "no profile and no direct list mean empty exclusions"
assert_contains "$minimal_out" 'hostname = "vpn.example.com"' "hostname comes from the records"
assert_contains "$minimal_out" 'addresses = ["1.2.3.4:443"]' "addresses list carries the endpoint"
assert_contains "$minimal_out" "has_ipv6 = true" "has_ipv6 defaults to true"
assert_contains "$minimal_out" 'username = "alice"' "username comes from the records"
assert_contains "$minimal_out" 'password = "s3cret"' "password comes from the records"
assert_contains "$minimal_out" 'custom_sni = ""' "custom_sni is always emitted, empty when unset"
assert_contains "$minimal_out" 'client_random = ""' "client_random is always emitted, empty when unset"
assert_contains "$minimal_out" "skip_verification = false" "skip_verification defaults to false"
assert_contains "$minimal_out" 'certificate = ""' "an absent PEM file yields the empty certificate"
assert_contains "$minimal_out" 'upstream_protocol = "http2"' "upstream_protocol defaults to http2"
assert_contains "$minimal_out" "anti_dpi = false" "anti_dpi defaults to false"
assert_contains "$minimal_out" "dns_upstreams = []" "no dns_upstream records means an empty list"
assert_contains "$minimal_out" "included_routes = []" "included_routes stays empty"
assert_contains "$minimal_out" "excluded_routes = []" "excluded_routes stays empty"
assert_contains "$minimal_out" "mtu_size = 1350" "mtu_size is the bare number, default 1350"
assert_contains "$minimal_out" "change_system_dns = false" "system dns is never changed"
assert_eq "0" "$(count_occ device_name "$minimal_out")" "device_name is never emitted"
assert_eq "0" "$(count_occ use_existing "$minimal_out")" "use_existing is never emitted"

# --- full fixture (vpn-mode profile assigned) ------------------------------------

full_out=$(sh "$GEN" tests/fixtures/records/full.tsv)

assert_contains "$full_out" 'loglevel = "debug"' "loglevel comes from the records"
assert_contains "$full_out" 'vpn_mode = "general"' "a vpn-mode profile keeps general mode"
assert_contains "$full_out" "post_quantum_group_enabled = false" "a stored zero disables post quantum"
assert_contains "$full_out" 'addresses = ["1.2.3.4:443", "[2001:db8::1]:443"]' \
    "every address record lands in the list"
assert_contains "$full_out" 'password = "pa\"ss\\with"' "quote and backslash are escaped, tabs cut the value"
assert_contains "$full_out" 'custom_sni = "vpn.example.com"' "custom_sni is emitted when populated"
assert_contains "$full_out" 'client_random = "0a0b0c/0f0f0f"' "client_random is emitted when populated"
assert_contains "$full_out" 'exclusions = ["bank.example", "*.local.example"]' \
    "a vpn-mode profile's bypass_rules become the exclusions"
assert_contains "$full_out" "skip_verification = true" "a stored one enables skip_verification"
assert_contains "$full_out" "has_ipv6 = false" "a stored zero disables has_ipv6"
assert_contains "$full_out" 'upstream_protocol = "http3"' "upstream_protocol comes from the records"
assert_contains "$full_out" "anti_dpi = true" "a stored one enables anti_dpi"
assert_contains "$full_out" 'dns_upstreams = ["tls://1.1.1.1", "quic://dns.adguard.com:8853"]' \
    "every dns_upstream record lands in the list"
assert_contains "$full_out" "mtu_size = 1400" "mtu_size comes from the records"
assert_eq "0" "$(count_occ legacy.example "$full_out")" \
    "domains.direct does not leak while a profile is assigned"

# --- bypass fixture (bypass-mode profile assigned) --------------------------------

bypass_out=$(sh "$GEN" tests/fixtures/records/bypass.tsv)

assert_contains "$bypass_out" 'vpn_mode = "selective"' "a bypass-mode profile selects selective mode"
assert_contains "$bypass_out" 'exclusions = ["telegram.org", "1.2.3.0/24"]' \
    "a bypass-mode profile's vpn_rules become the exclusions"
assert_eq "0" "$(count_occ bank.example "$bypass_out")" \
    "bypass_rules are not exclusions in bypass mode"
assert_eq "0" "$(count_occ legacy.example "$bypass_out")" \
    "domains.direct does not leak in bypass mode"

# --- stale reference: named profile does not exist --------------------------------

stale_tsv="$TT_TEST_TMP/stale.tsv"
printf 'main.enabled\t1\nendpoint.hostname\tvpn.example.com\nendpoint.address\t1.2.3.4:443\nendpoint.username\talice\nendpoint.password\ts3cret\nendpoint.routing_profile\tGhost\ndomains.direct\tbank.example\n' > "$stale_tsv"

stale_out=$(sh "$GEN" "$stale_tsv")

assert_contains "$stale_out" 'vpn_mode = "general"' "a stale profile reference falls back to general mode"
assert_contains "$stale_out" 'exclusions = ["bank.example"]' \
    "a stale profile reference falls back to the direct list"

# --- unknown profile mode ---------------------------------------------------------

unknown_tsv="$TT_TEST_TMP/unknown-mode.tsv"
printf 'main.enabled\t1\nendpoint.hostname\tvpn.example.com\nendpoint.address\t1.2.3.4:443\nendpoint.username\talice\nendpoint.password\ts3cret\nendpoint.routing_profile\tOdd\nrouting_profile.name\tOdd\nrouting_profile.mode\tsmart\nrouting_profile.vpn_rules\ttelegram.org\nrouting_profile.bypass_rules\tbank.example\ndomains.direct\tlegacy.example\n' > "$unknown_tsv"

unknown_out=$(sh "$GEN" "$unknown_tsv")

assert_contains "$unknown_out" 'vpn_mode = "general"' "an unknown profile mode falls back to general mode"
assert_contains "$unknown_out" 'exclusions = ["legacy.example"]' \
    "an unknown profile mode falls back to the direct list"
assert_eq "0" "$(count_occ telegram.org "$unknown_out")" \
    "vpn_rules are not used for an unknown profile mode"
assert_eq "0" "$(count_occ bank.example "$unknown_out")" \
    "bypass_rules are not used for an unknown profile mode"

# --- PEM emission -----------------------------------------------------------------

pem_file="$TT_TEST_TMP/cert.pem"
printf -- '-----BEGIN CERTIFICATE-----\nMIIBdummy\n-----END CERTIFICATE-----\n' > "$pem_file"

pem_out=$(sh "$GEN" tests/fixtures/records/minimal.tsv "$pem_file")

assert_contains "$pem_out" "certificate = '''" "a PEM file opens the multi-line literal"
assert_contains "$pem_out" "-----END CERTIFICATE-----" "the PEM body appears verbatim"
assert_contains "$pem_out" "'''" "the multi-line literal is closed"

# --- missing credentials -----------------------------------------------------------

bare_tsv="$TT_TEST_TMP/bare.tsv"
printf 'main.enabled\t1\n' > "$bare_tsv"

assert_exit 1 "missing credentials fail with status 1" sh "$GEN" "$bare_tsv"

cred_err=$(sh "$GEN" "$bare_tsv" 2>&1 >/dev/null)
assert_contains "$cred_err" "gen-config:" "the failure message names the script"
assert_contains "$cred_err" "endpoint.hostname is not set" "the failure message names the missing key"

tt_test_summary
