'use strict';

'require view';
'require form';
'require uci';
'require rpc';
'require ui';
'require dom';

// All settings live in one UCI config, so the page presents them as a
// single tabbed map: each section turns into a tab, and switching tabs is
// pure browser-side work, no router round-trip.
//
// The tabs are grouped by what the fields mean to the user rather than by
// the UCI layout: General (service state and the profile picker), Server
// (the connection), Security (TLS trust and anti-censorship), Routing
// profiles and Advanced (networking internals and the client's own DNS).
// Several option classes cover the same UCI section (endpoint) — that is
// fine, they all save to the same config.
var callImport = rpc.declare({
	object: 'luci.trusttunnel',
	method: 'import_config',
	params: [ 'text' ]
});

var callStatus = rpc.declare({
	object: 'luci.trusttunnel',
	method: 'status'
});

var callPing = rpc.declare({
	object: 'luci.trusttunnel',
	method: 'ping',
	params: [ 'target' ]
});

// Read-only one-liner for the General tab; the full verdict banner with
// Start/Stop lives on the Status page.
function statusSummary(st) {
	if (!st)
		return _('Status unavailable');

	if (!st.client_installed)
		return _('The TrustTunnel client is not installed');

	if (!st.running)
		return st.enabled ? _('The service is not running') : _('The service is off');

	if (!st.device_up)
		return _('Connecting to the server…');

	var head = st.device ? _('Running on %s').format(st.device) : _('Running');

	if (st.routing_profile)
		return _('%s — profile %s').format(head, st.routing_profile);

	return head;
}

return view.extend({
	load: function() {
		// The network config feeds the LAN device hint on the Advanced
		// tab; the status call feeds the Service line on the General tab.
		// A failure of either must not take the whole settings page down.
		return Promise.all([
			uci.load('trusttunnel'),
			uci.load('network').catch(function() { return null; }),
			callStatus().catch(function() { return null; })
		]);
	},

	handleImport: function() {
		var ta = E('textarea', {
			'rows': 14, 'style': 'width:100%',
			'placeholder': _('Paste the endpoint configuration generated by your server')
		});

		ui.showModal(_('Import endpoint configuration'), [
			E('p', {}, _('Accepts both forms a server hands out: the configuration file text and a tt:// link. Nothing is saved until you press Save & Apply.')),
			ta,
			E('div', { 'class': 'right' }, [
				E('button', { 'class': 'btn', 'click': ui.hideModal }, _('Cancel')),
				' ',
				E('button', {
					'class': 'cbi-button cbi-button-positive',
					'click': ui.createHandlerFn(this, function() {
						return callImport(ta.value).then(function(res) {
							if (res.error) {
								ui.addNotification(null, E('p', {}, res.error), 'danger');
								return;
							}

							// Every imported value is applied through the
							// pending save below: nothing is written until
							// the user presses Save & Apply.
							if (res.hostname)
								uci.set('trusttunnel', 'endpoint', 'hostname', res.hostname);
							if (res.username)
								uci.set('trusttunnel', 'endpoint', 'username', res.username);
							if (res.password)
								uci.set('trusttunnel', 'endpoint', 'password', res.password);
							if (res.certificate)
								uci.set('trusttunnel', 'endpoint', 'certificate', res.certificate);
							if (res.addresses && res.addresses.length)
								uci.set('trusttunnel', 'endpoint', 'address', res.addresses);
							if (res.custom_sni)
								uci.set('trusttunnel', 'endpoint', 'custom_sni', res.custom_sni);
							if (res.client_random)
								uci.set('trusttunnel', 'endpoint', 'client_random', res.client_random);
							if (res.protocol)
								uci.set('trusttunnel', 'endpoint', 'protocol', res.protocol);
							if (res.anti_dpi != null)
								uci.set('trusttunnel', 'endpoint', 'anti_dpi', res.anti_dpi);
							if (res.has_ipv6 != null)
								uci.set('trusttunnel', 'endpoint', 'has_ipv6', res.has_ipv6);
							if (res.skip_verification != null)
								uci.set('trusttunnel', 'endpoint', 'skip_verification', res.skip_verification);
							if (res.dns_upstreams && res.dns_upstreams.length)
								uci.set('trusttunnel', 'endpoint', 'dns_upstream', res.dns_upstreams);

							uci.save();
							ui.hideModal();
							ui.addNotification(null, E('p', {}, _('Imported. Review the fields and press Save & Apply.')), 'info');
							window.setTimeout(function() {
								location.reload();
							}, 800);
						}).catch(function(e) {
							ui.addNotification(null, E('p', {}, e.message || String(e)), 'danger');
						});
					})
				}, _('Import'))
			])
		]);
	},

	handleTest: function() {
		var box = E('div', {}, [
			E('p', { 'class': 'spinning' }, _('Pinging…'))
		]);

		ui.showModal(_('Test connection'), [
			E('p', {}, _('Loss and round-trip time for every configured address. The saved settings are used, so press Save & Apply first.')),
			box,
			E('div', { 'class': 'right' }, [
				E('button', { 'class': 'btn', 'click': ui.hideModal }, _('Close'))
			])
		]);

		callPing('').then(function(res) {
			if (res.error) {
				dom.content(box, E('p', res.error));
				return;
			}

			var rows = [
				E('tr', { 'class': 'cbi-section-table-row' }, [
					E('th', { 'class': 'cbi-section-table-cell' }, _('Host')),
					E('th', { 'class': 'cbi-section-table-cell' }, _('Loss')),
					E('th', { 'class': 'cbi-section-table-cell' }, _('min / avg / max'))
				])
			];

			(res.results || []).forEach(function(r) {
				rows.push(E('tr', { 'class': 'cbi-section-table-row' }, [
					E('td', { 'class': 'cbi-section-table-cell' }, r.host),
					E('td', { 'class': 'cbi-section-table-cell' }, r.loss + '%'),
					E('td', { 'class': 'cbi-section-table-cell' },
						r.avg === null ? '—' : r.min + ' / ' + r.avg + ' / ' + r.max + ' ms')
				]));
			});

			dom.content(box, E('table', { 'class': 'cbi-section-table' }, rows));
		}).catch(function(e) {
			dom.content(box, E('p', e.message || String(e)));
		});
	},

	render: function(data) {
		var st = data[2];

		var m = new form.Map('trusttunnel', _('TrustTunnel'));

		m.tabbed = true;

		var s, o;

		// Tab 1 — General: the service itself and the profile that applies.
		s = m.section(form.NamedSection, 'main', 'main', _('General'));
		s.description = _('When the service runs and which profile decides what goes through the tunnel.');

		o = s.option(form.DummyValue, '_status', _('Service'));
		o.cfgvalue = function() { return statusSummary(st); };

		o = s.option(form.Flag, 'enabled', _('Start on boot'),
			_('Whether the service starts when the router boots. The Start button on the Status page runs it right now.'));
		o.rmempty = false;

		o = s.option(form.ListValue, 'log_level', _('Log level'));
		o.value('info', 'info');
		o.value('debug', 'debug');
		o.value('trace', 'trace');
		o.description = _('debug and trace write a lot; leave them on only while investigating something.');

		o = s.option(form.ListValue, 'routing_profile', _('Routing profile'),
			_('The named profile that decides what goes through the tunnel. Profiles are managed on the Routing profiles tab.'));
		o.value('', _('None — everything through the tunnel'));

		// Names are read through the uci module API (current LuCI
		// resolves uci.load() with the package-name list, so the load()
		// result is no source of config data). The endpoint's stored
		// assignment is appended too when it references a profile that has
		// been deleted, so that reference keeps saving (legacy fallback).
		var profiles = uci.sections('trusttunnel', 'routing_profile') || [];
		var current = uci.get('trusttunnel', 'endpoint', 'routing_profile');
		var currentKnown = false;

		for (var i = 0; i < profiles.length; i++) {
			o.value(profiles[i].name, profiles[i].name);

			if (profiles[i].name === current)
				currentKnown = true;
		}

		if (current && !currentKnown)
			o.value(current, current);

		// Tab 2 — Server: the connection to the server.
		s = m.section(form.NamedSection, 'endpoint', 'endpoint', _('Server'));
		s.description = _('How the client reaches your server. The Import… button is the fast path.');

		o = s.option(form.Button, '_import', _('Server configuration'),
			_('The fast path: paste what your server generated and the fields below fill themselves in.'));
		o.inputtitle = _('Import…');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleImport');

		o = s.option(form.DynamicList, 'address', _('Addresses'),
			_('host:port or [ipv6]:port. With several addresses the client measures them and picks the fastest.'));
		o.placeholder = '203.0.113.10:443';
		o.rmempty = false;

		o = s.option(form.Value, 'hostname', _('TLS host name'),
			_('Used for the TLS session, not for routing. Without it many servers refuse the connection.'));
		o.datatype = 'hostname';
		o.rmempty = false;

		o = s.option(form.Value, 'username', _('User name'));
		o.rmempty = false;

		o = s.option(form.Value, 'password', _('Password'));
		o.password = true;
		o.rmempty = false;

		o = s.option(form.ListValue, 'protocol', _('Transport'));
		o.value('http2', 'HTTP/2');
		o.value('http3', 'HTTP/3 (QUIC)');
		o.description = _('QUIC is often faster, but some networks throttle or block UDP.');

		o = s.option(form.Flag, 'has_ipv6', _('Server carries IPv6'));
		o.default = '1';

		o = s.option(form.Button, '_test', _('Connection test'),
			_('Loss and round-trip time for every configured address. Uses the saved settings, so press Save & Apply first.'));
		o.inputtitle = _('Test connection');
		o.inputstyle = 'action';
		o.onclick = ui.createHandlerFn(this, 'handleTest');

		// Tab 3 — Security: TLS trust and anti-censorship.
		s = m.section(form.NamedSection, 'endpoint', 'endpoint', _('Security'));
		s.description = _('TLS trust and anti-censorship. These rarely need manual changes after importing the server configuration.');

		o = s.option(form.Flag, 'anti_dpi', _('Anti-DPI'),
			_('Countermeasures against traffic inspection. Worth enabling if the connection establishes but keeps dropping.'));

		o = s.option(form.Flag, 'post_quantum', _('Post-quantum key exchange'));
		o.default = '1';

		o = s.option(form.Value, 'custom_sni', _('Custom SNI'),
			_('Overrides the TLS Server Name. Needed when the server answers on an address that does not match its host name, e.g. behind a CDN or an IP-only setup.'));
		o.placeholder = 'example.com';
		o.optional = true;
		o.validate = function(section_id, value) {
			if (!value)
				return true;

			var v = value.toLowerCase();

			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Use the format example.com');

			return true;
		};

		o = s.option(form.Value, 'client_random', _('Client Random, hex prefix'),
			_('TLS Client Random prefix and mask. Anti-scan servers accept only clients with the matching prefix. Format: abcdef or abcdef/0f0f0f.'));
		o.placeholder = '0a0b0c/0f0f0f';
		o.optional = true;
		o.validate = function(section_id, value) {
			if (!value)
				return true;

			if (value.length > 64)
				return _('At most 64 characters');

			var parts = value.split('/');

			if (parts.length > 2 || !parts[0] || !/^[0-9a-f]+$/i.test(parts[0]))
				return _('Enter hex digits only, e.g. 0a0b0c or 0a0b0c/0f0f0f');

			if (parts[0].length % 2 !== 0)
				return _('The hex prefix must be a whole number of bytes');

			if (parts.length === 2) {
				if (!/^[0-9a-f]+$/i.test(parts[1]) || parts[1].length % 2 !== 0)
					return _('The mask must be hex digits, a whole number of bytes');

				if (parts[1].length !== parts[0].length)
					return _('The mask must be the same length as the prefix');
			}

			return true;
		};

		o = s.option(form.Flag, 'skip_verification', _('Skip certificate verification'),
			_('Accepts any certificate, which removes the protection against a substituted server. Pin the certificate below instead whenever you can.'));

		o = s.option(form.TextValue, 'certificate', _('Pinned certificate (PEM)'),
			_('Leave empty to use the system trust store, which requires the ca-bundle package.'));
		o.rows = 6;
		o.optional = true;

		// Tab 4 — Routing profiles: named rule sets.
		// TypedSection: current LuCI's form module exports no plain
		// `Section` class.
		s = m.section(form.TypedSection, 'routing_profile', _('Routing profiles'));
		s.addremove = true;
		s.anonymous = true;
		s.sortable = true;
		s.description = _('A profile decides what goes through the tunnel. VPN mode tunnels everything except the bypass rules; bypass mode tunnels only the VPN rules. Rules accept a domain, *.domain, an IP address, IP:port, or a CIDR range.');

		// Rules may name a domain, *.domain, an address, address:port or a
		// CIDR block. The client performs the strict validation; this check
		// only rejects values that are obviously wrong.
		function validateRule(value) {
			if (!value)
				return true;

			var v = value.toLowerCase();

			// The special form *:port accepts any destination on that port.
			if (/^\*:[0-9]+$/.test(v))
				return true;

			if (/^\*\./.test(v))
				v = v.slice(2);

			// Plain numeric/hex address forms (with or without a port)
			// are accepted without further checks.
			if (/^[0-9a-f:.\[\]\/]+$/.test(v))
				return true;

			if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/.test(v))
				return _('Not a valid domain, IP address or CIDR range');

			return true;
		}

		o = s.option(form.Value, 'name', _('Name'),
			_('Unique name; the General tab assigns a profile by it.'));
		o.optional = false;
		o.validate = function(section_id, value) {
			if (!value)
				return _('Name is required');

			var secs = uci.sections('trusttunnel', 'routing_profile') || [];

			for (var i = 0; i < secs.length; i++)
				if (secs[i]['.name'] !== section_id && secs[i].name === value)
					return _('Another profile already has this name');

			return true;
		};

		o = s.option(form.ListValue, 'mode', _('Mode'));
		o.value('vpn', _('VPN — tunnel everything except the bypass rules'));
		o.value('bypass', _('Bypass — tunnel only the VPN rules'));
		o.default = 'vpn';
		o.rmempty = false;

		o = s.option(form.DynamicList, 'vpn_rules', _('VPN rules'),
			_('Sent through the tunnel: in bypass mode these are the only destinations that go through; in VPN mode the list has no effect.'));
		o.placeholder = 'telegram.org';
		o.validate = validateRule;

		o = s.option(form.DynamicList, 'bypass_rules', _('Bypass rules'),
			_('Always sent out directly: in VPN mode these are the only destinations that bypass the tunnel; in bypass mode the list has no effect.'));
		o.placeholder = 'bank.example';
		o.validate = validateRule;

		// Tab 5 — Advanced: networking internals and the client's own DNS.
		s = m.section(form.NamedSection, 'network', 'network', _('Advanced'));
		s.description = _('These rarely need changing. MTU is the exception: too high a value makes small pages load while TLS handshakes and large downloads stall.');

		o = s.option(form.Value, 'mtu', _('MTU'));
		o.datatype = 'range(576,9000)';
		o.default = '1350';

		o = s.option(form.Value, 'lan_devices', _('LAN interfaces'),
			_('Space-separated list whose forwarded traffic is considered. Empty means the device of the lan network.'));
		o.optional = true;

		// The lan device is read from the network config so the empty-value
		// behaviour is spelled out instead of being a mystery.
		var lanDevice = uci.get('network', 'lan', 'device') || '';

		if (lanDevice) {
			o.description += ' ' + _('Detected: %s').format(lanDevice);
			o.placeholder = lanDevice;
		}
		else {
			o.placeholder = 'br-lan';
		}

		o = s.option(form.Flag, 'blackhole_on_down', _('Drop traffic when the tunnel is down'),
			_('Adds a blackhole route so marked traffic is dropped instead of leaking to the provider.'));
		o.default = '1';

		o = s.option(form.Flag, 'include_router_traffic', _('Route the router\'s own traffic too'),
			_('By default only forwarded LAN traffic is routed. Enabling this also routes traffic originated by the router itself.'));

		o = s.option(form.DynamicList, 'dns_upstream', _('DNS used by the client itself'),
			_('Applies to what the TrustTunnel client resolves on its own — for example the exclusion domains it pre-resolves. Empty means the client default, AdGuard DNS unfiltered.'));
		o.placeholder = 'tls://1.1.1.1';
		o.value('tls://1.1.1.1', 'Cloudflare — DNS over TLS');
		o.value('tls://9.9.9.9', 'Quad9 — DNS over TLS');
		o.value('tls://dns.adguard-dns.com', 'AdGuard — DNS over TLS');
		o.value('https://cloudflare-dns.com/dns-query', 'Cloudflare — DNS over HTTPS');
		o.value('https://dns.quad9.net/dns-query', 'Quad9 — DNS over HTTPS');
		o.value('quic://dns.adguard-dns.com', 'AdGuard — DNS over QUIC');
		o.value('1.1.1.1:53', 'Cloudflare — ' + _('plain DNS'));
		o.value('9.9.9.9:53', 'Quad9 — ' + _('plain DNS'));

		o = s.option(form.Value, 'fwmark', _('Firewall mark'),
			_('Decimal or 0x-prefixed hexadecimal. Change only on a conflict with mwan3, SQM or another package that marks packets.'));
		o.default = '0x9527';
		o.validate = function(section_id, value) {
			if (!value)
				return true;

			if (!/^(0x[0-9a-fA-F]{1,8}|[0-9]{1,10})$/.test(value))
				return _('Enter a decimal number or 0x-prefixed hexadecimal');

			if (!/^0x/i.test(value) && +value > 4294967295)
				return _('Enter a decimal number no greater than 4294967295');

			return true;
		};

		o = s.option(form.Value, 'table', _('Routing table'),
			_('Any table id except 0 and the reserved 253-255.'));
		o.datatype = 'uinteger';
		o.default = '880';
		o.validate = function(section_id, value) {
			if (!value)
				return true;

			if (!/^[0-9]+$/.test(value) || +value < 1 || +value > 4294967294)
				return _('Enter a table id between 1 and 4294967294');

			if (+value >= 253 && +value <= 255)
				return _('Table ids 253, 254 and 255 are reserved by the system');

			return true;
		};

		return m.render();
	}
});
